version: '3.7'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/gases_content:/var/lib/postgresql/data

  web:
    build: .
    command: python3.9 /usr/src/GasesContent/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/GasesContent/
    ports:
      - "8000:8000"
    depends_on:
      - db